name: app
description:

version: 0.0.0

dependencies:
  flutter:
    sdk: flutter
  fluro: ^1.3.1
  synchronized: ^1.5.0+1
  http: ^0.11.3+16
  intl: ^0.15.7
  sqflite: ^0.11.0+1
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sprites/
    - assets/sprites/items/
